baseURL = 'https://edriablog.github.io/'
languageCode = 'en-us'
title = 'Yijue (Edria) Li'
theme = 'typo'

# Disable tags, actually, they are rendered as a list, but the idea is to disable them.
disableKinds = ['taxonomy']

# Google analytics code
googleAnalytics = "G-xxxxxxxxxx"

[params]
math = true
# Appearance
theme = 'auto'

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntroTitle = 'Welcome to my page!'
homeIntroContent = """
I have started my journey of data science and machine learning since 2022, when after several years of legal practice I went back to school at University of Washington and joined the Department of Applied Mathematics in pursuing my Applied and Computational Mathematics master degree (check out my [resume here](resume)!). 

I have learned a lot! Changing gear is difficult, but with passion you thrive and survive!

Join me on this journey as I continue to learn in the realm of applied mathematics, data analysis, machine learning, deep neural networks, computer vision, natural language processing and more! Let me know your thoughts and connect with me on LinkedIn or email me at edriali@outlook.com. 

Together, let's push the boundaries of what's possible and craft solutions that shape the future.
"""

# Collection to display on home page: 
# in this case we would display content/posts pages
homeCollectionTitle = 'Posts'
homeCollection = 'posts'


# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/yijueli"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@your-name"

[[params.social]]
name = "github"
url = "https://github.com/edriablog"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"
[[params.menu]]
name = "resume"
url = "/resume"
[[params.menu]]
name = "posts"
url = "/posts"



# Syntax highlight on code blocks, all styles: 
# https://xyproto.github.io/splash/docs/all.html
# I suggest algol
[markup]
[markup.highlight]
style = 'algol'